# ===== Polkit Agent =====
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ===== Wallpaper =====
exec-once = hyprpaper

# ===== Notification Daemon =====
exec-once = mako

# ===== Application Launcher Background Service =====
exec-once = walker --gapplication-service

# ===== Elephant (Walker backend) =====
exec-once = elephant

# ===== Clipboard History =====
exec-once = wl-paste --watch cliphist store

# ===== Idle Daemon =====
exec-once = hypridle

# ===== UWSM Check =====
exec-once = ~/.local/share/dotfiles/bin/check-uwsm
