layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar
layerrule = blur on, match:namespace launcher
layerrule = ignore_alpha 0, match:namespace launcher
layerrule = blur on, match:namespace notifications
layerrule = ignore_alpha 0.5, match:namespace notifications
layerrule = no_anim on, match:namespace hyprpicker
layerrule = no_anim on, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0.41, match:namespace walker
